metno/snap

README.md
src/Makefile
src/common/snap.F90
src/ubuntuBionic.mk
src/ubuntuLucid.mk
src/ubuntuLustre.mk
src/ubuntuLustreIntel.mk
src/ubuntuLustreSnappy.mk
src/version.py

This pull request adds a runtime check for the version of snap currently in use. This can be invoked with e.g.
```
bsnap_naccident --version
```
This falls back on the git hash if VERSION is not given as environment variable
Currently gives an empty version when building from the subdirectories
Should we refine this approach, or document that releases must be created from the src directory?

add version flag

---

utils/SnapPy/snapRemoteRunner.py

This changes output directory from 
'%Y-%m-%dT%M%H%S', i.e., YYYY-MM-DDTMMHHSS (note minutes and hours)
to
'%Y-%m-%dT%H%M%S', i.e., YYYY-MM-DDTHHMMSS

Changed bug in run directory (swapped hour/minute)

---

utils/SnapPy/Snappy/BrowserWidget.py
utils/SnapPy/Snappy/EEMEP/Controller.py
utils/SnapPy/Snappy/EEMEP/resources/startScreenVolc.html

A few fixes in this PR, the most important is automatic handling of 23+ km ASL eruptions
- 23+ km above sea level eruptions are truncated to 23 km above sea level (removing ash above 23 km)
- QtWebKitWidgets is deprecated. Added automatic loading of new classes. 
- Slight updates to GUI to emphasize above sea level / above vent

Added fix for 23+ km eruptions

---

src/common/find_parameters_fi.f90
src/ubuntuBionic.mk

The SLIM files contains a rotated lat-lon grid, which we has not been tested with the automatic parameter finding. This PR adds the necessary parsing of the proj string to convert to `gparam`

proj to rotated longlat

---

src/test/snapunittest.py

To avoid numeric noise in tests, use a minimum difference of 0.1 (whichever unit).

use 0.1 as lower limit for tests

---

utils/SnapPy/snap4rimsterm

Argos to Snap translation is now able to start a snap-run with minute resolution by prepending a 0Bq release from full hour to the real release start time.

using a 0Bq release during minutes-offset from non-hour startup

---

src/common/snap.F90

Error case previously lead to probing for a variable called "" (empty), with a confusing error message

ensure nctype is set before autodetection

---

src/common/filesort_fi.f90
src/common/find_parameters_fi.f90

The fimex backend was opening files and not closing them. This caused OOM conditions for one of my model setups. Valgrind revealed 16GB in memory leaks...

close fimex files after use

---

src/COMPILE.md
src/gcc_pkgconfig.mk

Adds a minimal makefile configuration which uses `pkg-config ` and `nf-config` to add libraries. This makes it easier to use for platforms which supports these methods for overriding the installed library.

Autodetection of libraries

---

src/common/fldout_nc.f90
src/common/snap.F90
src/common/snap.mk
src/common/snapdebugML.F90
src/common/snapdebugML.f90
src/common/wetdep.f90
utils/component_times_from_log.py

Adds timer functionality which is used to track the time spent on individual components of the SNAP model. The python script can be used to plot the time spent both per iteration and per (iteration, particle) during a run without requiring the model to finish execution

Component time tracking

---

src/common/releasefile.f90
src/common/snap.F90

Setting a release through the releasefile was currently broken, and has been fixed.
A new functionality has been added: `release.radius` and friends can now be specified as scalars instead of arrays, which should make specifying a fixed radius, upper, or lower release bound a bit friendlier.

Fix releasefile

---

utils/SnapPy/Snappy/Resources.py

There was an extra } in the input dir path when using EC global meteorology. This made running global simulation with EC meteorology crash.

Removed } from _MET_GLOBAL_INPUTDIRS for NrpaEC0p1Global

---

src/common/filesort_nc.f90
src/common/readfield_nc.f90
src/gcc_pkgconfig.mk

Current behaviour is to panic on faulty meteorology (e.g. only partial sync). The new behaviour is instead to ignore the file if there is some error on reading it

Skip meteo on error

---

utils/SnapPy/Snappy/Resources.py
utils/SnapPy/Snappy/resources/fillValue_template.ncml
utils/SnapPy/Snappy/resources/removeSnapReferenceTime.ncml
utils/SnapPy/nc2grib.py
utils/SnapPy/snap4rimsterm

Use 0 as fill-value before converting to grib. fimex-grib-translation will use the fill-value as bitmap mask and only write data not corresponding to that bitmap. Data-reduction for a typical 68h run, 7 components: 4x 388MB -> 4x 15MB (> factor 20).
Currently, bitmap packing is the only grib-compression algorithm supported by argos.

Grib bitmap

---

src/common/readfield_nc.f90
src/common/snap.F90
src/common/snapmetML.f90

Adds unit checking for future meteorology

Remove ec_n1s

---

src/common/fldout_nc.f90
src/common/readfield_fi.f90
src/common/readfield_nc.f90

Intel compiler put all associate variables on the stack, which isn't large enough for SNAPs typical arrays. When using the -heap-array option with the intel compiler, the binary has heavy memory leaks. See #92.
Not all code changed has been tested, in particular the special output (aircraft doserates/column-concentrations) and the fimex-reading. The latter is done by the automated test, not sure about the special outputs.

removing all associate statements, fix segfault in ifort #92

---

utils/SnapPy/Snappy/EcMeteorologyCalculator.py
utils/SnapPy/Snappy/MeteorologyCalculator.py
utils/SnapPy/Snappy/Resources.py
utils/SnapPy/Snappy/SnapController.py
utils/SnapPy/Snappy/resources/snap.input_ec_0p1.tmpl
utils/SnapPy/Snappy/resources/startScreen.html
utils/SnapPy/debian.bionic/control
utils/SnapPy/snap4rimsterm
utils/SnapPy/snapRunnerNpp

Enabling to SnapPy, snapRunnerNpp and snap4rimsterm to read directly from the ec_atoms_*_3h.nc files rather than converting first to emep-input files. This makes it possible to run up to 10 day forecasts.

Ec global direct

---

src/common/readfield_fi.f90
src/common/readfield_nc.f90
src/common/snapfilML.f90
src/common/snapmetML.f90

Precip deaccumulation could in special cases deaccumulate against the wrong file or not perform a deaccumulation step
Common setups do not experience any of these special cases

Fix precip deaccumulation

---

src/common/particleML.f90
src/common/rmpart.f90

Avoid numerical subnormals not being removed from the model by setting a slightly higher limit of Bq/model-particle to 1000.*1e-38(=positive_subnormal).

set the minimul Bq per model-particle to a very low number

---

utils/SnapPy/README.md
utils/SnapPy/Snappy/SnapJobEC.py
utils/SnapPy/snapRemoteRunner.py

Needing a new status code to differ between `send to queue` and `running in queue` for monitoring. First code should not remain without being handled for 10min, second should be handled within 2h. Should not affect ARGOS, but since it is a change to the user, it is a moderate rather than minor change.

Status codes

---

install_usermodule_r8.sh
src/common/fldout_nc.f90

As far as I can tell `p0` is unused in the output file and can be omitted
Fixes #107

Only set surface_air_pressure

---

src/common/rwalk.f90
src/test/Makefile
src/test/snap_forward_test.py

Reducing the horizontal diffusion base-time form 60min to 15min. This was never documented anywhere (only for vertical diffusion) and was recently set to 60min. Since the horizontal diffusion has been tested at a time where SNAP was run with ~50km resolution meteorology, 15min timesteps were common, so the original horizontal diffusion was more similar to a setting with 15min base-time.
The bias with the 15min baseline for the etex results (above) are just slightly worse than the bias with the 60min (below), and acceptable. 
This PR partly reverts yesterdays horizontal diffusion change to a more conservative approach by not changing too much in SNAP without extensive testing.

Conservative horizontal diffusion

---

utils/SnapPy/Snappy/SnapJobEC.py
utils/SnapPy/snapRemoteRunner.py

Downloads may fail if file-upload has not finished completely. Using rsync for atomic uploads (tempfile+move) instead of scp.

atomic uploads using rsync

---

install_usermodule_r8.sh
src/common/fimex.f90
src/common/snap.F90
utils/SnapPy/Snappy/Resources.py
utils/SnapPy/Snappy/SnapController.py
utils/SnapPy/Snappy/resources/snap.in
utils/SnapPy/snapEnsPlot.py

This PM allows SnapPy to plot with a newer bdiana version with de jure rather than de facto country-borders. In addition, country-codes are plotted again, and a test-dataset is removed.
PS: Sorry, the branch-name is completely misleading, this branch has nothing to do with meps.

Smaller graphics fixes

---

utils/SnapPy/Snappy/EEMEP/Controller.py
utils/SnapPy/Snappy/EEMEP/SixHourMax.py
utils/SnapPy/Snappy/EEMEP/resources/startScreenVolc.html
utils/SnapPy/debian.jammy/control

Using a default of 0.05 for fine-ash fraction and a peak to mean ratio of 1 for ash-calculations following
Beckett, F.M.; Witham, C.S.; Leadbetter, S.J.; Crocker, R.; Webster, H.N.; Hort, M.C.; Jones, A.R.; Devenish, B.J.; Thomson, D.J. Atmospheric Dispersion Modelling at the London VAAC: A Review of Developments since the 2010 Eyjafjallajökull Volcano Ash Cloud. Atmosphere 2020, 11, 352. https://doi.org/10.3390/atmos11040352 
Allowing manually change of fine-ash fraction in user interface to either a new value or to original default, i.e. taken from Mastin et al (2009b) Table 3.

Implement changes in Ash emissions and products following VAAC London

---

utils/SnapPy/Snappy/EcMeteorologyCalculator.py
utils/SnapPy/Snappy/ICONMeteorologyCalculator.py
utils/SnapPy/Snappy/MeteorologyCalculator.py

Calculate the usable timesteps from the input NWP datasets for ICON rather than hardcoding.
Using up to 4 NWP datasets for ICON runs to always have 60+ hours of forecast. Currently, 00 and 12 have at maximum 48h, while 06 and 18 have 120.

Icon timesteps

---

src/common/bldp.f90
src/common/find_parameters.f90
src/common/find_parameters_fi.f90
src/common/om2edot.f90
src/common/readfield_fi.f90
src/common/readfield_nc.f90
src/common/snap.F90
src/common/snapdimML.f90
src/common/snapgrdML.f90
src/test/find_parameters_fi_test.f90

Simplifying the code for level selection by removing `kadd` functionality, I don't think we have used the `kadd` functionality in some time and I suspect it is broken
Fixes an off-by-one bug in using xwind as 10m wind, which causes issues for re-running ETEX

Simplify klevel/remove kadd

---

src/common/decay.f90
src/common/release.f90
src/common/snap.F90
src/common/snap.mk

Fix bomb-dose decay formula to start at H+1 with H+1 (1hour after bomb) emissions. No decay before H+1, which means that results the first hour are heavily underpredicted, which was expected anyway.
The old code applied the decay strength at H+1 to H+0, and at H+2 to H+1. Since the bomb-decay is a power and not a exponential decay, this was over-estimating decay by a factor ~2-3. In addition, it did not take into account releases occuring after model-start (full hour).

fix bomb-dose decay formula to start at H+1

---

src/common/decay.f90
src/common/drydep.f90
src/common/wetdep.f90
utils/SnapPy/Snappy/SnapController.py
utils/SnapPy/Snappy/SnapInputBomb.py

- fixing minutes when snapPy startTime has minute offset for both NPP and Bomb releases
- fix seg-faults in bomb-runs with merged output where dry/wet/decay was still using runtime output-positions rather than merged output-positions
fixes #140

snappy window ignores minutes in release start time

---

src/common/drydep.f90
src/common/fldout_nc.f90
src/common/readfield_fi.f90
src/common/readfield_nc.f90
src/common/snap.F90
src/common/snap.mk

Porting of the reading of the extra variables required for dry and wet deposition using netcdf. Testing by comparing the two readers side by side which produces virtually identical results

netcdf reader for dry/wet-deposition

---

utils/SnapPy/Snappy/SnapController.py

This PR solves the problem when a server cannot start a process within 3s. Rather than continuing execution, it terminates the process. 
The PR gives now error-codes of started subprocesses.
The PR removes now also a workaround for old PyQt version which crashed when a thread is deleted, e.g. keep threads running foreaver. That workaround gives in newer PyQt versions an exception during shutdown.

Better error-handling on hanging machine

---

src/common/release.f90
src/common/snap.F90

For very short release-step, e.g. equal to model-timesteps, 300s, rounding errors might skip a release. E.g. 300s release steps around model step 34 35 and 36 would look like
```
>>> x = [2.82999992, 2.92000008, 3.00000000]
>>> print([y*12 for y in x])
[33.95999904, 35.04000096, 36.0]
```
and model step 34 had been omitted in integer comparison.
This PR rounds to the closest integer, and omits therefore the problem.

fix rounding errors on release-steps close to model-time steps

---

utils/SnapPy/Snappy/EEMEP/Controller.py
utils/SnapPy/Snappy/Utils.py

small tweaks fixing issues encountered while running with coordinates copy-pasted from advisories like this https://ds.data.jma.go.jp/svd/vaac/data/TextData/2025/20250707_28209000_0056_Text.html or this https://www.ospo.noaa.gov/VAAC/ARCH25/REVE/2025B151220.html

Fix volcano height log + coord parsing 

---

src/common/snap.F90

Within the AROME products there might be inconsistencies in the name of the variables. I propose the ability to override certain names but still being able to default from an nctype

Make met names overridable

---

src/common/readfield_nc.f90

This supports the most common transformations (identity and Pa -> hPa) and makes SNAP a little safer to use on unknown meteorology or misconfigured `nctype`

Simple units checks
