- utils/SnapPy/Snappy/EEMEP/Controller.py
Removes duplicate of code which is just below.
> Fixed duplicate code

- src/common/snap.F90
- src/common/snaptabML.f90
- src/common/wetdep.f90
- src/debug.mk
> Remove wetdep1

- utils/SnapPy/Snappy/EEMEP/Controller.py
If a user is in queue, and volcano.xml is deleted before the new volcano.log file is created it will report that someone (else) deleted your run. Now it waits for one second from volcano.xml has disappeared until checking if volcano.log has been created. Only then will it let the user know that the run has been deleted.
> Tries to fix possible race condition in GUI

- src/common/fldout_nc.f90
> put vtrans values during define

- utils/SnapPy/Snappy/Resources.py
Tested on PPI, and can now find the files again
> restore meps

- src/common/release.f90
- src/common/snap.F90
- src/common/snapargosML.f90
- src/common/snapdebugML.f90
- src/common/snapfilML.f90
- src/common/snapfldML.f90
- src/common/snapgrdML.f90
- src/common/snapparML.f90
- src/common/snapposML.f90
Removing some variables that are not read from, and renaming some variables
> Small changes

- src/common/find_parameters_fi.f90
Detection of grid-parameters for polar-stereographic projections when reading with fimex.
> implementing polar-stereographic for fi-detection

- src/common/filesort_fi.f90
- src/common/filesort_nc.f90
- src/common/readfield_fi.f90
- src/common/readfield_nc.f90
- src/common/snap.F90
- src/common/snapfilML.f90
Implement and ignore spinup-steps. Keep reference to spinup steps for deaccumulation if needed.
> Spinup deaccumulate precip

- src/common/fimex.f90
- src/common/readfield.f90
- src/common/readfield_fi.f90
- src/common/readfield_nc.f90
I found a few more memory around missing fimex-close operations - and the fortran final keyword, which should solve the problem in the future.
Adding also a warning when too many precipitation fields are requested, not really connect to fimex, but was just looking at the code.
> Fimex memleaks

- utils/SnapPy/Snappy/EEMEP/Resources.py
- utils/SnapPy/Snappy/EcMeteorologyCalculator.py
- utils/SnapPy/Snappy/ICONMeteorologyCalculator.py
- utils/SnapPy/Snappy/Resources.py
This code is tested with ICON global meteo, MEPS and EC default meteorolgoy. Still needs testing with eemep.
> only reading from STORE or .lustredir variable

- src/common/allocateFields.f90
- src/common/filesort_fi.f90
- src/common/find_parameters_fi.f90
- src/common/fldout_nc.f90
- src/common/posint.f90
- src/common/readfield_fi.f90
- src/common/readfield_nc.f90
- src/common/releasefile.f90
- src/common/snap.F90
- src/common/snapdimML.f90
- src/common/snapfimexML.f90
- src/common/snapfldML.f90
- src/common/snapgrdML.f90
`fldout_nc` has now been split into init/accumulate/output subroutines, making the code easier to understand.
> Simplify output routines

- utils/SnapPy/Snappy/EEMEP/ModelRunner.py
Global Meteorology calculation failed for volcanoes outside the default domain. This patch fixes it.
> Fix global eemep

- utils/SnapPy/Snappy/EEMEP/Resources.py
- utils/SnapPy/Snappy/Resources.py
- utils/SnapPy/Snappy/ResourcesCommon.py
- utils/SnapPy/Snappy/resources/lustredir_serviceenv.sh
- utils/SnapPy/debian.bionic/control
tested for both eemep and snap with current storeA settings
> enabling mapp-service to read lustre-selection

- src/common/readfield_nc.f90
- src/common/snap.F90
- src/common/snapfilML.f90
Possible fix for #67 
Needs to be tested with a suitable `snap.input`
> Make forecast.input inclusive

- src/common/fldout_nc.f90
> Replace xy with lonlat

- src/common/snap.F90
> Remove debug nonsense

- .github/workflows/test.yml
- src/common/snap.mk
- src/gcc_pkgconfig.mk
This runs our existing tests on each PR/push to any branch. The run takes about 35 minutes, with output as here: https://github.com/magnusuMET/snap/actions/runs/1260591940
@heikoklein Please enable github actions for this repository
> Add testing through CI

- utils/SnapPy/Snappy/EEMEP/ModelRunner.py
Adding additional log-handler to stderr to be warned of errors/warnings when running on console or cron
> adding logging of warnings to stderr

- install_usermodule_r8.sh
Requires a clean environment to prevent libproj from reading /modules
> bdiana wrapper in r8 module

- .github/workflows/test.yml
- src/gcc_pkgconfig.mk
Upgrading github test-environment from bionic to jammy.
> using jammy as test-machine

- src/common/allocateFields.f90
- src/common/checkDomain.f90
- src/common/compheight.f90
- src/common/decay.f90
- src/common/drydep.f90
- src/common/fldout_nc.f90
- src/common/posint.f90
- src/common/readfield_fi.f90
- src/common/readfield_nc.f90
- src/common/snap.F90
- src/common/snapdimML.f90
- src/common/snapfldML.f90
- src/common/wetdep.f90
Coming projects required output in very high resolution, up to 100m. Lagrangian models carry model particles with exact coordinates and are have therefore not restricted to the grid of the meteorological driver. While it is already possible to interpolate the meteorology to high resolution using the FimexIO, this becomes very cost inefficient for such high resolutions. This PR allows therefore to just increase the output resolution to i.e. 25 times the input resolution, while working internally with the original meteorological resolution.
> Hires output

- utils/SnapPy/Snappy/resources/snap.in
- utils/SnapPy/snapRunnerNpp
Fixing plotting of borders on top of colors.
Fixing diana color-maps for time of arrival plots.
> Borders colors

- utils/SnapPy/Snappy/AddBombIsotopes.py
- utils/SnapPy/Snappy/Resources.py
- utils/SnapPy/Snappy/SnapJob.py
- utils/SnapPy/Snappy/resources/isotopes_template.xml
- utils/SnapPy/snapNc2grib.py
Adding column output to grib-files for ARGOS
Adding column_concentrations to output from bombs
> Column output

- install_usermodule_r8.sh
Heads up that dependency managment is going to be painful if we need to upgrade: conda does not want to resolve the current dependencies (not even when running for 2 days) and more recent versions requires updated libc
> Add --force option (and safeguard)

- utils/SnapPy/snap4rimsterm
Main task in latest commit, deleting symlinks before creating new ones. Needed when re-running a snap4rimsterm job.
Formatted snap4rimsterm with black and changed format() to f-strings before applying changes.
> Fix symlink

- utils/SnapPy/Snappy/Resources.py
- utils/SnapPy/snapRunnerNpp
- utils/SnapPy/snapRunnerNpps
move runs done from snapRunnerNpp or snapRunnerNpps to a separated outputdirectory to have a better overview of the current on-demand output directories.
> Separate cronruns

- src/common/drydep.f90
- src/common/fldout_nc.f90
- src/common/readfield_fi.f90
- src/common/snapmetML.f90
Dry deposition parametrisation is now seasonal
> Updates to deposition parametrisation to make it work for MEPS

- utils/SnapPy/Snappy/EEMEP/resources/Mastin_et_al_2009a_table3.csv
Can someone with write access to the main branch add this change? Only Langjokull added for now, I will check the list for missing volcanoes later.
> Langjokull added to list, same type as Hveravellir

- utils/SnapPy/Snappy/EEMEP/Controller.py
As recognized during the last ash-exercise, volcanic ash emissions would always start at the last full hour, independently if minutes-resolution was given or not. This PR respects now minute in the start-time.
Several format statements in the Controller.py have also been converted to f-strings for better readability.
> allow minute resolution for eemep; format to f-strings

- .github/workflows/test.yml
- src/common/bldp.f90
- src/common/compheight.f90
- src/common/forwrd.F90
- src/common/readfield_fi.f90
- src/common/readfield_nc.f90
- src/common/release.f90
- src/common/snap.F90
- src/common/snapgrdML.f90
- src/common/snapmetML.f90
- src/common/snaptabML.f90
Reverts metno/snap#170
Problems with undefined upper layers.
> Revert "Vertical coords cleanup"

- .github/workflows/test.yml
- src/common/bldp.f90
- src/common/compheight.f90
- src/common/forwrd.F90
- src/common/readfield_nc.f90
- src/common/release.f90
- src/common/snaptabML.f90
Cherry-pick vertical cleanups from previous PR
> Vertical cleanup2
